services:
  db:
    image: postgres:16
    container_name: recipes_postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - recipes_pgdata:/var/lib/postgresql/data

volumes:
  recipes_pgdata:
